name: websafe_svg
description: Simple abstraction to be able to use SVGs in Android, iOS, and Web.
version: 2.0.0-nullsafety
homepage: https://github.com/peiffer-innovations/websafe_svg
environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.24.0-6.0.pre"

dependencies:
  convert: ^2.1.1
  flutter:
    sdk: flutter
  flutter_svg: ^0.20.0-nullsafety.3
  http: ^0.12.2
  logging: ^0.11.4
  meta: ^1.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
